#!/usr/bin/env bash

if [ $# -ne 1 ]
then
    echo "USAGE : ./moulinette file.c" ; exit
fi

gcc ./correction/correct.c $1 -O3

timeout 1 ./a.out map.txt

if [ $? -eq 124 ]
then
    echo "You timed out!"
elif [ $? -eq 0 ]
then
     echo "Congratulations! c:"
else
    echo "Sorry, you failed!"
fi

rm ./a.out
